name: C++ Build

on:
  push:
    branches: [ ci_test ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build HW1
        run: msbuild HW1/HW1.sln /p:Configuration=Debug

      - name: Build HW2
        run: msbuild HW2/HW2.sln /p:Configuration=Debug

      - name: Build HW3
        run: msbuild HW3/HW3.sln /p:Configuration=Debug

      - name: Build HW4
        run: msbuild HW4/HW4.sln /p:Configuration=Debug